### ISSUE TITLE
[Enhancement] The ability to select server in the client

### ISSUE THREAD

**Issue by ben132** [caffeine239/Unity-Wow-Clone#1]
My suggestion is to have a box on the Client login screen to allow for the selection of servers to connect to, rather that a file with the data stored.
I am glad that I found a project like this. One that seems to be in some sort of development, hopefully still in development.

**Comment by caffeine239** [comment]
> My suggestion is to have a box on the Client login screen to allow for the selection of servers to connect to, rather that a file with the data stored. I am glad that I found a project like this. One that seems to be in some sort of development, hopefully still in development.

been awhile since ive touched any of it. My pc has been down for about a month, but i got it back up last night.

**Comment by ben132** [comment]
I wish I knew how to do any coding I did a course in software development, where we learnt basically nothing in about software development.

**Comment by caffeine239** [comment]
This will be added in the next push.
